.\"
.\" Copyright (c) 2014-2021, Frederic Cambus
.\" https://github.com/fcambus/dnc
.\"
.\" dnc is released under the BSD 2-Clause license.
.\" See LICENSE file for details.
.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.Dd $Mdocdate: November 8 2021 $
.Dt DNC 1
.Os
.Sh NAME
.Nm dnc
.Nd Check domain names configuration
.Sh SYNOPSIS
.Nm
.Op Fl 46hmnsv
.Ar domain
.Sh DESCRIPTION
.Nm
(Domain Name Checker), is a CLI tool to check domain names configuration.
.Pp
The options are as follows:
.Bl -tag -width 10n
.It Fl 4
Resolve and display A records (IPv4 addresses).
.It Fl 6
Resolve and display AAAA records (IPv6 addresses).
.It Fl h
Display usage.
.It Fl m
Resolve and display MX records (Mail Exchange).
.It Fl n
Resolve and display NS records (Name Servers).
.It Fl s
Display SSL/TLS certificate expiration date.
.It Fl v
Display version.
.El
.Sh AUTHORS
.Nm
was written by
.An Frederic Cambus .
